# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"4\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08image_id\x18\x02 \x01(\t\"o\n\x16\x43lassificationResponse\x12\x17\n\x0fpredicted_class\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x16\n\x0einference_time\x18\x03 \x01(\x01\x12\x10\n\x08image_id\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\xa3\x01\n\x10InferenceService\x12K\n\rClassifyImage\x12\x17.inference.ImageRequest\x1a!.inference.ClassificationResponse\x12\x42\n\x0bHealthCheck\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=30
  _globals['_IMAGEREQUEST']._serialized_end=82
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=84
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=195
  _globals['_HEALTHREQUEST']._serialized_start=197
  _globals['_HEALTHREQUEST']._serialized_end=212
  _globals['_HEALTHRESPONSE']._serialized_start=214
  _globals['_HEALTHRESPONSE']._serialized_end=263
  _globals['_INFERENCESERVICE']._serialized_start=266
  _globals['_INFERENCESERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
